"""create guest credits table

Revision ID: b55e4149cc3d
Revises: f96ceaaaae0c
Create Date: 2025-02-05 00:25:13.421095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55e4149cc3d'
down_revision: Union[str, None] = 'f96ceaaaae0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_ip_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_ip_credits_id'), 'guest_ip_credits', ['id'], unique=False)
    op.create_index(op.f('ix_guest_ip_credits_ip_address'), 'guest_ip_credits', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_ip_credits_ip_address'), table_name='guest_ip_credits')
    op.drop_index(op.f('ix_guest_ip_credits_id'), table_name='guest_ip_credits')
    op.drop_table('guest_ip_credits')
    # ### end Alembic commands ###
